export default interface VodInfoType {
    info: {
        kinopoisk_url: string
        tmdb_id: string
        name: string
        o_name: string
        cover_big: string
        movie_image: string
        releasedate: string
        episode_run_time: string
        youtube_trailer: string
        director: string
        actors: string
        cast: string
        description: string
        plot: string
        age: string
        mpaa_rating: string
        rating_count_kinopoisk: number
        country: string
        genre: string
        duration_secs: number
        duration: string
        video: {
            index: number
            codec_name: string
            codec_long_name: string
            profile: string
            codec_type: string
            codec_time_base: string
            codec_tag_string: string
            codec_tag: string
            width: number
            height: number
            coded_width: number
            coded_height: number
            has_b_frames: number
            sample_aspect_ratio: string
            display_aspect_ratio: string
            pix_fmt: string
            level: number
            chroma_location: string
            refs: number
            quarter_sample: string
            divx_packed: string
            r_frame_rate: string
            avg_frame_rate: string
            time_base: string
            start_pts: number
            start_time: string
            duration_ts: number
            duration: string
            bit_rate: string
            nb_frames: string
            disposition: Disposition
        },
        audio: {
            index: number
            codec_name: string
            codec_long_name: string
            codec_type: string
            codec_time_base: string
            codec_tag_string: string
            codec_tag: string
            sample_fmt: string
            sample_rate: string
            channels: number
            channel_layout: string
            bits_per_sample: number
            dmix_mode: string
            ltrt_cmixlev: string
            ltrt_surmixlev: string
            loro_cmixlev: string
            loro_surmixlev: string
            r_frame_rate: string
            avg_frame_rate: string
            time_base: string
            start_pts: number
            start_time: string
            duration_ts: number
            duration: string
            bit_rate: string
            nb_frames: string
            disposition: Disposition
        },
        bitrate: number
        rating: string
    },
    movie_data: {
        stream_id: number
        name: string
        added: string
        category_id: string
        container_extension: string
        custom_sid: string
        direct_source: string
    }
}

interface Disposition {
    default: number
    dub: number
    original: number
    comment: number
    lyrics: number
    karaoke: number
    forced: number
    hearing_impaired: number
    visual_impaired: number
    clean_effects: number
    attached_pic: number
    timed_thumbnails: number
}